server:
  servlet:
    context-path: /springboot03
  port: 8088

#properties文件和YML文件同时存在并且有相同的配置，properties文件优先级更高
#user:
#  username: admin
#  age: 18
#  status: true
#  birthday: 2022/11/9
#  address:
#    province: 重庆市
#    city: 重庆市
#  lists:
#    - list1
#    - list2
#    - list3
#  maps: {k1: v1,k2: v2}

#指定要激活的配置
spring:
  profiles:
    active: test


---

spring:
  profiles: dev
server:
  port: 9991
---

spring:
  profiles: test
server:
  port: 9992

---
spring:
  profiles: prod
server:
  port: 9993

